---
- name: Retrieve vaulted secrets
  hosts: localhost
  connection: local
  gather_facts: false
  # This repo will FAIL TO RUN if you do not have vaulted_secrets_repository, vaulted_secrets_repository_key and vaulted_secrets_repository_passphrase defined!

  # Retrieve the secrets from the repository
  tasks:
    - name: Create temporary private key file
      ansible.builtin.copy:
        content: "{{ vaulted_secrets_repository_key }}"
        dest: "/tmp/temp_git_key"
        mode: "0600"
      register: temp_key_file

    - name: "Pull the secrets from the repository"
      ansible.builtin.git:
        repo: "{{ vaulted_secrets_repository }}"
        dest: "{{ playbook_dir }}/secrets"
        version: main
        force: true
        key_file: "/tmp/temp_git_key"

    - name: Remove temporary private key file
      ansible.builtin.file:
        path: "{{ temp_key_file.dest }}"
        state: absent

    - name: "Load the vaulted variables based on the name of our inventory"
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/secrets/environments/{{ inventory_dir | basename }}.yml"
