---
- name: Retrieve vaulted secrets
  hosts: localhost
  connection: local
  gather_facts: false
  # This repo will FAIL TO RUN if you do not have vaulted_secrets_repository, vaulted_secrets_repository_key and vaulted_secrets_repository_passphrase defined!

  # Retrieve the secrets from the repository
  tasks:
    - name: Create temporary private key file
      ansible.builtin.copy:
        content: "{{ vaulted_secrets_repository_key }}"
        dest: "/tmp/temp_git_key"
        mode: "0600"
      register: temp_key_file

    - name: Ensure ~/.ssh exists
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.ssh"
        state: directory
        mode: '0700'

    - name: Add GitHub's host keys to known_hosts # noqa line-length
      ansible.builtin.known_hosts:
        name: github.com
        key: "github.com {{ item }}"
        state: present
      loop:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"
        - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="

    - name: "Pull the secrets from the repository"
      ansible.builtin.git:
        accept_hostkey: true
        repo: "{{ vaulted_secrets_repository }}"
        dest: "{{ playbook_dir }}/secrets"
        version: main
        force: true
        key_file: "/tmp/temp_git_key"

    - name: Remove temporary private key file
      ansible.builtin.file:
        path: "{{ temp_key_file.dest }}"
        state: absent

    - name: "Load the vaulted variables based on our environment name"
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/secrets/environments/{{ ehi_environment_name }}.yml"
      register: loaded_vars

    - name: Set variables for all hosts
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"
      loop: "{{ loaded_vars.ansible_facts | dict2items }}"
      delegate_to: "{{ inventory_hostname }}"
      delegate_facts: true
