---
# Global settings for all PostgreSQL clusters.
patroni_scope: {{ postgresql_cluster_name }}

patroni_system_group: postgres
patroni_install_haproxy: false
patroni_install_watchdog_loader: false
patroni_postgresql_version: 14
patroni_etcd_hosts: "{% for host in groups[{{ postgresql_cluster_name }}] %}{{ hostvars[host]['inventory_hostname_short'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"  # yamllint disable-line rule:line-length
patroni_etcd_protocol: https
patroni_etcd_cacert: "/var/lib/patroni.pki/ca.pem"
patroni_etcd_cert: "/var/lib/patroni.pki/{{ inventory_hostname }}.pem"
patroni_etcd_key: "/var/lib/patroni.pki/{{ inventory_hostname }}-key.pem"
patroni_postgresql_connect_address: "{{ ansible_ens18.ipv4.address }}:5432"
patroni_restapi_connect_address: "{{ ansible_ens18.ipv4.address }}:{{ patroni_restapi_port }}"